name: Deploy html

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    concurrency:
      group: "pages"
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5


      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './me'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
